image: Visual Studio 2017
build:
  parallel: true
platform:
  - x64
  - x86
configuration:
  - Debug
  - Release
environment:
  matrix:
    - PYTHON: 27
    - PYTHON: 33
    - PYTHON: 34
    - PYTHON: 35
    - PYTHON: 36

matrix:
  exclude:
    - configuration: Release
      PYTHON: 33
    - configuration: Release
      PYTHON: 34
    - configuration: Release
      PYTHON: 35
    - platform: x86
      PYTHON: 33
    - platform: x86
      PYTHON: 34
    - platform: x86
      PYTHON: 35
    - configuration: Release
      platform: x86

install:
  - ps: |
      if ($env:PLATFORM -eq "x64") { $env:CMAKE_ARCH = "x64" }
      if ($env:PYTHON) {
        if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
        $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      }
build_script:
  - cmake -G "Visual Studio 15 2017" -A "%CMAKE_ARCH%" -DCMAKE_SUPPRESS_REGENERATION=1 -DCMAKE_CXX_FLAGS="/MP"
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmake --build . --config "%CONFIGURATION%" --target install -- /v:m /logger:%MSBuildLogger%
test_script:
  - cd installed
  - python -c "import parselmouth"